SELECT FP1.CATEGORY, FP1.PRICE AS MAX_PRICE, FP1.PRODUCT_NAME
FROM FOOD_PRODUCT FP1,
    (SELECT DISTINCT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY) FP2
WHERE FP1.CATEGORY IN ('과자','국','김치','식용유')
AND FP1.PRICE=FP2.MAX_PRICE
ORDER BY MAX_PRICE DESC