SELECT 
    HDF.HISTORY_ID,
    CASE 
        WHEN 7<=HDF.DF AND HDF.DF<30
            THEN ROUND(HDF.DF*HDF.DAILY_FEE*(1-(
                SELECT DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE CAR_TYPE='트럭'
                AND DURATION_TYPE LIKE '7%')/100))
        WHEN 30<=HDF.DF AND HDF.DF<90
            THEN ROUND(HDF.DF*HDF.DAILY_FEE*(1-(
                SELECT DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE CAR_TYPE='트럭'
                AND DURATION_TYPE LIKE '30%')/100))
        WHEN 90<=HDF.DF
            THEN ROUND(HDF.DF*HDF.DAILY_FEE*(1-(
                SELECT DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE CAR_TYPE='트럭'
                AND DURATION_TYPE LIKE '90%')/100))
        ELSE ROUND(HDF.DF*HDF.DAILY_FEE)
        END AS FEE
FROM 
    (SELECT H.HISTORY_ID, C.DAILY_FEE,
    DATEDIFF(H.END_DATE,H.START_DATE)+1 AS DF
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID=H.CAR_ID
    WHERE C.CAR_TYPE='트럭') HDF
ORDER BY FEE DESC, H.HISTORY_ID DESC
