SELECT A.YEAR, A.MONTH,A.USER_CNT AS PURCHASED_USERS, 
    ROUND(A.USER_CNT/(SELECT COUNT(*)
                        FROM USER_INFO
                        WHERE JOINED BETWEEN DATE('2021-01-01') AND DATE('2021-12-31')),1) AS PURCHASED_RATIO
FROM 
    (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT UI.USER_ID) AS USER_CNT
    FROM ONLINE_SALE OS, USER_INFO UI
    WHERE OS.USER_ID=UI.USER_ID
    AND UI.JOINED BETWEEN DATE('2021-01-01') AND DATE('2021-12-31')
    GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE)) A
ORDER BY YEAR ASC, MONTH ASC
