SELECT P.PRODUCT_CODE,
CASE 
WHEN SUM(O.SALES_AMOUNT)*P.PRICE !=0 THEN SUM(O.SALES_AMOUNT)*P.PRICE
ELSE 0
END
AS SALES 
FROM PRODUCT P LEFT JOIN OFFLINE_SALE AS O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC,
PRODUCT_CODE ASC