SELECT MONTH(H1.START_DATE) AS MONTH, H1.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H1,
(SELECT CAR_ID, COUNT(*) AS CNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID
HAVING COUNT(*) >= 5) H2
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND H1.CAR_ID=H2.CAR_ID
GROUP BY MONTH(H1.START_DATE),H1.CAR_ID
ORDER BY MONTH ASC
,CAR_ID DESC;


