SELECT USU.USER_ID,USU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_USER USU
ON UGB.WRITER_ID=USU.USER_ID
WHERE UGB.STATUS='DONE'
GROUP BY USU.USER_ID
HAVING SUM(UGB.PRICE)>=700000
ORDER BY TOTAL_SALES ASC