SELECT RI_1.FOOD_TYPE, RI_1.REST_ID, RI_1.REST_NAME, RI_1.FAVORITES
FROM REST_INFO RI_1,
(SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE) RI_2
WHERE RI_1.FOOD_TYPE=RI_2.FOOD_TYPE
AND RI_1.FAVORITES=RI_2.FAVORITES
ORDER BY RI_1.FOOD_TYPE DESC;